<?php
$ui->assign('nav0',$nav0);
$ui->assign('nav1',$nav1);
$ui->assign('nav2',$nav2);
$ui->assign('nav3',$nav3);
$ui->assign('nav4',$nav4);
$ui->assign('nav5',$nav5);
$ui->assign('nav6',$nav6);
$ui->assign('nav7',$nav7);
$ui->assign('nav8',$nav8);
$ui->assign('nav9',$nav9);
$ui->assign('nav10',$nav10);
$ui->assign('sub_menu',$sub_menu);
$ui->assign('plugin_ui_header',$plugin_ui_header);